// <auto-generated />
namespace WorldCuisinesRestaurants.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class dec072 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dec072));
        
        string IMigrationMetadata.Id
        {
            get { return "201812080112245_dec072"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
